//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> MaTacGia { get; set; }
    
        public virtual TacGia TacGia { get; set; }
    }
}
